version: '3'
services:
    nginx:
        container_name: timeonmars-nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 8000:80
        networks:
            - symfony
    php:
        container_name: timeonmars-php-fpm
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www
        networks:
            - symfony

networks:
    symfony:
        driver: bridge